/**
 * Story 9.3: the Spectate manifest, and the one place a wall-clock is read.
 *
 * `public/replays/manifest.json` is the single source of truth for the loop
 * order and for "where would a visitor arriving right now be in it" (AD-17:
 * the default stream is a manifest walk, never a computation trigger). This
 * module owns two things and nothing else:
 *
 *   1. Fetching and structurally validating that document.
 *   2. `offsetForNow`, a **pure** function of `(manifest, nowMs)` that answers
 *      the mid-loop-join question.
 *
 * `offsetForNow` is the only place in the whole `spectate/` tree permitted to
 * take a timestamp as input, and it is called exactly once, at panel mount
 * (`panel.ts`). Everything downstream -- `walk.ts`, the `PlaybackClock`, the
 * renderer -- stays frame-counted (INV-3 unchanged): the offset only ever
 * selects *where to start looking*, never *what happens*, so a Match's
 * `finalStateHash` is provably unaffected by which real-world moment a
 * visitor happened to arrive (AD-15).
 */

/**
 * The one permitted wall-clock read in the whole `apps/web` player (a
 * deliberate, documented exception to INV-3's usual "no wall-clock anywhere"
 * rule -- see `source-discipline.test.ts`'s carve-out for this file and only
 * this file).
 *
 * A visitor arriving at the site has to be shown a loop already in progress,
 * and that requires knowing what time it is *once*, at mount. Isolating the
 * read behind this one-line function -- rather than calling `Date.now()`
 * inline at the call site -- is what keeps `panel.ts` and every test able to
 * inject a fixed value instead of depending on the real clock, and is what
 * keeps the read itself confined to a single grep-able line.
 */
export function readNowMs(): number {
  return Date.now();
}

export interface SpectateManifestEntry {
  readonly id: string;
  readonly commandLogUrl: string;
  readonly reasoningUrl?: string;
  readonly schemaVersion: string;
  readonly frameCount: number;
}

export interface SpectateManifest {
  readonly schemaVersion: string;
  /** A fixed anchor epoch, chosen once when the manifest was generated -- never `Date.now()` at generation time either. */
  readonly loopStartEpochMs: number;
  readonly totalLoopDurationMs: number;
  readonly entries: readonly SpectateManifestEntry[];
}

export interface FetchResponse {
  readonly ok: boolean;
  readonly status: number;
  json(): Promise<unknown>;
}

function fail(message: string): never {
  throw new Error(`Invalid Spectate manifest: ${message}`);
}

function asRecord(value: unknown, where: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    fail(`${where} must be an object.`);
  }
  return value as Record<string, unknown>;
}

function requireString(source: Record<string, unknown>, field: string, where: string): string {
  const value = source[field];
  if (typeof value !== 'string' || value.trim() === '') {
    fail(`${where}.${field} must be a non-empty string.`);
  }
  return value as string;
}

function requireNonNegativeInt(source: Record<string, unknown>, field: string, where: string): number {
  const value = source[field];
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0) {
    fail(`${where}.${field} must be a non-negative whole number.`);
  }
  return value as number;
}

function parseEntry(raw: unknown, index: number): SpectateManifestEntry {
  const where = `entries[${String(index)}]`;
  const source = asRecord(raw, where);
  const id = requireString(source, 'id', where);
  const commandLogUrl = requireString(source, 'commandLogUrl', where);
  const schemaVersion = requireString(source, 'schemaVersion', where);
  const frameCount = requireNonNegativeInt(source, 'frameCount', where);

  const reasoningUrlRaw = source['reasoningUrl'];
  if (reasoningUrlRaw !== undefined && (typeof reasoningUrlRaw !== 'string' || reasoningUrlRaw.trim() === '')) {
    fail(`${where}.reasoningUrl must be a non-empty string when present.`);
  }

  const entry: SpectateManifestEntry = {
    id,
    commandLogUrl,
    schemaVersion,
    frameCount,
    ...(reasoningUrlRaw === undefined ? {} : { reasoningUrl: reasoningUrlRaw as string }),
  };
  return Object.freeze(entry);
}

/**
 * Structurally validates a fetched manifest document.
 *
 * Deliberately not a full JSON-Schema validation: unlike a Command Log, this
 * document is generated by this repo's own build script (`build-spectate-
 * manifest.mts`), never by a visitor or a third party, so a hand-written
 * shape check is proportionate -- the same posture `startup.ts` takes toward
 * the demo log's "cast, not validation".
 */
export function validateSpectateManifest(candidate: unknown): SpectateManifest {
  const source = asRecord(candidate, 'the manifest');
  const schemaVersion = requireString(source, 'schemaVersion', 'the manifest');
  const loopStartEpochMs = requireNonNegativeInt(source, 'loopStartEpochMs', 'the manifest');
  const totalLoopDurationMs = requireNonNegativeInt(source, 'totalLoopDurationMs', 'the manifest');

  const entriesRaw = source['entries'];
  if (!Array.isArray(entriesRaw)) {
    fail('entries must be an array.');
  }
  if (entriesRaw.length === 0) {
    fail('entries must contain at least one entry.');
  }

  const entries = entriesRaw.map((raw, index) => parseEntry(raw, index));

  // `panel.ts`'s picker and `walk.ts`'s `playSpecific` both resolve an entry
  // by `id` -- a duplicate id would make every entry sharing it unreachable
  // except the first `findIndex` match, silently. Caught here rather than at
  // the point of confusion.
  const seenIds = new Set<string>();
  for (const entry of entries) {
    if (seenIds.has(entry.id)) {
      fail(`entries contains a duplicate id "${entry.id}".`);
    }
    seenIds.add(entry.id);
  }

  const manifest: SpectateManifest = {
    schemaVersion,
    loopStartEpochMs,
    totalLoopDurationMs,
    entries: Object.freeze(entries),
  };
  return Object.freeze(manifest);
}

export interface FetchLike {
  (url: string): Promise<FetchResponse>;
}

/** Same-origin, per the no-remote-asset sweep in `style-discipline.test.ts`, mirroring `startup.ts`'s `DEMO_REPLAY_URL`. */
export const SPECTATE_MANIFEST_URL = '/replays/manifest.json';

export async function fetchSpectateManifest(fetchImpl: FetchLike): Promise<SpectateManifest> {
  const response = await fetchImpl(SPECTATE_MANIFEST_URL);
  if (!response.ok) {
    throw new Error(`could not load ${SPECTATE_MANIFEST_URL} (HTTP ${String(response.status)})`);
  }
  return validateSpectateManifest(await response.json());
}

export interface LoopOffset {
  readonly entryIndex: number;
  readonly frameOffset: number;
}

/**
 * The pure heart of this module: given the manifest and "now", which entry
 * and which frame offset into it would a visitor arriving at this instant
 * see?
 *
 * A single-entry manifest, or a `nowMs` before `loopStartEpochMs`, both land
 * on `{ entryIndex: 0, frameOffset: 0 }` -- there is no meaningful "mid-loop"
 * position before the loop has started, and one entry has nowhere else to
 * wrap to. `totalLoopDurationMs` is trusted over a recomputation from
 * `frameCount` -- both are written by the same generation script, and this
 * function's contract is "trust the manifest", the same contract `walk.ts`
 * has toward each entry's own `frameCount`.
 */
export function offsetForNow(manifest: SpectateManifest, nowMs: number): LoopOffset {
  const totalFrames = manifest.entries.reduce((sum, entry) => sum + entry.frameCount, 0);
  if (totalFrames <= 0 || manifest.totalLoopDurationMs <= 0) {
    return { entryIndex: 0, frameOffset: 0 };
  }

  const sinceAnchorMs = nowMs - manifest.loopStartEpochMs;
  // Negative (before the anchor) or the loop having run past its own declared
  // length are both folded into a single non-negative modulus rather than
  // treated as errors: a manifest may be regenerated with a longer or shorter
  // loop than the moment a build script last ran, and a stale anchor must
  // never crash the panel.
  const cycleMs = sinceAnchorMs % manifest.totalLoopDurationMs;
  const positionMs = cycleMs < 0 ? cycleMs + manifest.totalLoopDurationMs : cycleMs;

  // Convert to a frame position within the concatenated loop, then walk the
  // entries to find which one that frame falls inside. Frames, not
  // milliseconds, are the unit `walk.ts` and the clock actually use -- this
  // conversion happens once, here, so nothing downstream repeats it.
  const positionFrames = Math.min(
    totalFrames - 1,
    Math.floor((positionMs / manifest.totalLoopDurationMs) * totalFrames),
  );

  let cursor = 0;
  for (let index = 0; index < manifest.entries.length; index += 1) {
    const entry = manifest.entries[index];
    if (entry.frameCount <= 0) {
      continue;
    }
    if (positionFrames < cursor + entry.frameCount) {
      return { entryIndex: index, frameOffset: positionFrames - cursor };
    }
    cursor += entry.frameCount;
  }

  // Every frame accounted for and none matched -- floating-point rounding at
  // the very top of the loop. Land on the last frame of the last non-empty
  // entry rather than throwing: an off-by-one here is a visitor joining one
  // frame later than ideal, not a crash.
  for (let index = manifest.entries.length - 1; index >= 0; index -= 1) {
    if (manifest.entries[index].frameCount > 0) {
      return { entryIndex: index, frameOffset: manifest.entries[index].frameCount - 1 };
    }
  }
  return { entryIndex: 0, frameOffset: 0 };
}
