import { CLIP_FRAME_COUNTS, CLIP_NAMES, type ClipName } from './animation';

/**
 * Story 4.1: loading a sprite sheet, and the contract a replacement must meet.
 *
 * The sheet that ships is generated by
 * `apps/web/scripts/build-sprite-sheet.mts` -- authored in this repo, so its
 * licence is this repo's. It is not meant to be the final art. Swapping in a
 * real CC0 sheet (the Martial Hero family, or anything else) is a matter of
 * dropping the image into `public/sprites/` and describing its rows in the
 * layout JSON; **no rendering code changes**, which is the whole reason this
 * indirection exists.
 *
 * The layout is validated on load rather than trusted. A sheet that is missing
 * a clip, or that promises more frames than its image can contain, fails here
 * with a sentence naming the problem -- the alternative is `drawImage` reading
 * outside the bitmap and silently painting nothing, which looks exactly like a
 * fighter that stopped animating.
 */

/** The narrow image surface `drawImage` needs. Declared structurally, like `Canvas2D`. */
export interface SpriteImage {
  readonly width: number;
  readonly height: number;
}

export interface ClipLayout {
  /** Row index in the sheet. */
  readonly row: number;
  readonly frames: number;
}

export interface SpriteSheetLayout {
  readonly image: string;
  readonly frameWidth: number;
  readonly frameHeight: number;
  readonly clips: Readonly<Record<string, ClipLayout>>;
}

export interface SpriteFrame {
  readonly sx: number;
  readonly sy: number;
  readonly sw: number;
  readonly sh: number;
}

export interface SpriteSheet {
  readonly image: SpriteImage;
  readonly frameWidth: number;
  readonly frameHeight: number;
  /** Source rectangle for one frame of one clip. Clamped, never out of bounds. */
  frameFor(clip: ClipName, frame: number): SpriteFrame;
}

function fail(detail: string): never {
  throw new Error(`Sprite sheet layout is unusable: ${detail}`);
}

function positiveInteger(value: unknown, where: string): number {
  if (!Number.isSafeInteger(value) || (value as number) <= 0) {
    fail(`${where} must be a positive safe integer, got ${String(value)}`);
  }
  return value as number;
}

/**
 * Validates a layout document and returns it typed.
 *
 * Every clip in `CLIP_NAMES` must be present. A sheet is allowed to supply
 * *more* frames than `CLIP_FRAME_COUNTS` asks for -- a richer sheet is a
 * welcome upgrade and `animationFor` simply will not reach the extras -- but
 * never fewer, because a short clip means `frameFor` clamps and the pose stops
 * advancing halfway through a Commitment Window.
 */
export function validateSpriteSheetLayout(candidate: unknown): SpriteSheetLayout {
  if (typeof candidate !== 'object' || candidate === null || Array.isArray(candidate)) {
    fail('the document is not an object');
  }

  const layout = candidate as Record<string, unknown>;
  if (typeof layout.image !== 'string' || layout.image.trim().length === 0) {
    fail('`image` must be a non-empty string');
  }
  if (layout.image.startsWith('http://') || layout.image.startsWith('https://')) {
    // Same reason the fonts are self-hosted: the site must render identically
    // offline and in CI, and a third-party host is a dependency someone else
    // can withdraw.
    fail(`\`image\` must be same-origin, got ${layout.image}`);
  }

  const frameWidth = positiveInteger(layout.frameWidth, 'frameWidth');
  const frameHeight = positiveInteger(layout.frameHeight, 'frameHeight');

  if (typeof layout.clips !== 'object' || layout.clips === null) {
    fail('`clips` must be an object');
  }
  const clips = layout.clips as Record<string, unknown>;

  const validated: Record<string, ClipLayout> = {};
  for (const name of CLIP_NAMES) {
    const entry = clips[name];
    if (typeof entry !== 'object' || entry === null) {
      fail(`no layout for clip "${name}"`);
    }
    const record = entry as Record<string, unknown>;
    const row = record.row;
    if (!Number.isSafeInteger(row) || (row as number) < 0) {
      fail(`clips.${name}.row must be a non-negative safe integer, got ${String(row)}`);
    }
    const frames = positiveInteger(record.frames, `clips.${name}.frames`);
    if (frames < CLIP_FRAME_COUNTS[name]) {
      fail(
        `clip "${name}" supplies ${String(frames)} frame(s) but the animation needs ${String(CLIP_FRAME_COUNTS[name])}`,
      );
    }
    validated[name] = Object.freeze({ row: row as number, frames });
  }

  return Object.freeze({
    image: layout.image,
    frameWidth,
    frameHeight,
    clips: Object.freeze(validated),
  });
}

/**
 * Binds a validated layout to a loaded image.
 *
 * `frameFor` clamps rather than throwing. A clamp draws the last frame of the
 * clip, which is a visible-but-sane degradation; throwing would abort the
 * animation-frame callback and freeze playback on whatever was last painted.
 */
export function createSpriteSheet(image: SpriteImage, layout: SpriteSheetLayout): SpriteSheet {
  const required = {
    width: layout.frameWidth * Math.max(...Object.values(layout.clips).map((clip) => clip.frames)),
    height: layout.frameHeight * (Math.max(...Object.values(layout.clips).map((clip) => clip.row)) + 1),
  };

  if (image.width < required.width || image.height < required.height) {
    fail(
      `image is ${String(image.width)}x${String(image.height)} but the layout needs at least ` +
        `${String(required.width)}x${String(required.height)}`,
    );
  }

  return Object.freeze({
    image,
    frameWidth: layout.frameWidth,
    frameHeight: layout.frameHeight,

    frameFor(clip: ClipName, frame: number): SpriteFrame {
      const entry = layout.clips[clip];
      const column = Math.max(0, Math.min(entry.frames - 1, Math.floor(frame)));
      return {
        sx: column * layout.frameWidth,
        sy: entry.row * layout.frameHeight,
        sw: layout.frameWidth,
        sh: layout.frameHeight,
      };
    },
  });
}
